config/routes.rb
Rails.application.routes.draw do
  resources :mahasiswas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mahasiswa.rb
class Mahasiswa < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mahasiswas_controller.rb
class MahasiswasController < ApplicationController

  # refactor controller
  before_action :current_mahasiswa, only: [:show, :edit, :update, :destroy]

  # Menampilkan seluruh data mahasiswa
  def index
    @mahasiswas = Mahasiswa.all
  end

  # Menampilkan data mahasiswa yang dipilih
  def show
    # @mahasiswa = Mahasiswa.find(params[:id])
  end
  
  # menampilkan form untuk menambahkan mahasiswa
  def new
    @mahasiswa = Mahasiswa.new
  end
  
  # menyimpan data mahasiswa baru menggunakan parameter
  def create
    @mahasiswa = Mahasiswa.new(mahasiswa_params)
    if @mahasiswa.save
      redirect_to mahasiswas_path
    else
      render 'new'
      # kembali kehalaman form tambah mahasiswa
    end
  
  end

  #menampilkan data mahasiswa yang akan di edit ke form
  def edit
    # @mahasiswa = Mahasiswa.find(params[:id])
  end
  
  #menyimpan data mahasiswa yang telah diedit
  def update
    @mahasiswa = Mahasiswa.find(params[:id])

    if @mahasiswa.update(mahasiswa_params)   
      redirect_to mahasiswas_path
    else
      render 'edit'
      # kembali kehalaman edit mahasiswa
    end

  end

  # menghapus data mahasiswa yang dipilih
  def destroy
    # @mahasiswa = Mahasiswa.find(params[:id])
    @mahasiswa.destroy
    
    redirect_to mahasiswas_path
  end

  private
  def mahasiswa_params
    params.require(:mahasiswa).permit(:nama, :jurusan)  
  end
  
  def current_mahasiswa
    @mahasiswa = Mahasiswa.find(params[:id])  #refactor controller
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mahasiswas_helper.rb
module MahasiswasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <!-- menambahkan bootstrap -->
    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <!-- end -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mahasiswas/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Edit  Mahasiswa</h1>
            <%= form_with model: @mahasiswa do |form| %>

                <%= form.text_field(:nama, {:class => 'form-control col-md-3'}) %>
                <%= form.text_field(:jurusan,  {:class => 'form-control col-md-3'}) %>
                <%= form.submit("Update", {:class => 'btn btn-info'}) %>

            <% end %>
        </div>
    </div>
</div>

app/views/mahasiswas/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Daftar Mahasiswa <%= link_to  "Add", new_mahasiswa_path, :class => 'btn btn-primary' %></h1> <br><br>
            <table class="table">
                <thead>
                    <th>Nama</th>
                    <th>Aksi</th>
                </thead>
                <tbody>
                    <% @mahasiswas.each do |mahasiswa| %>
                    <tr>
                        <td><%= mahasiswa.nama %></td>
                        <td>
                            <%= link_to  "Lihat", mahasiswa_path(mahasiswa), :class => 'btn btn-info' %>
                            <%= link_to 'Edit', edit_mahasiswa_path(mahasiswa), :class => 'btn btn-success' %>
                            <%= link_to 'Destroy', mahasiswa_path(mahasiswa),
                                method: :delete,
                                data: { confirm: 'Are you sure?' } , :class => 'btn btn-danger' %>
                        </td>
                    </tr>    
                    <% end %>

                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/mahasiswas/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Tambah Mahasiswa</h1>

            <%= form_with model: @mahasiswa do |form| %>

                <%= form.text_field(:nama, {:class => 'form-control col-md-3'}) %>
                <%= form.text_field(:jurusan,  {:class => 'form-control col-md-3'}) %>
                <%= form.submit("Add", {:class => 'btn btn-info'}) %>

            <% end %>
        </div>
    </div>
</div>

app/views/mahasiswas/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Detail Mahasiswa</h1>
            <h2>Nama Mahasiswa : <%= @mahasiswa.nama %></h2>
            <h4>Jurusan : <%= @mahasiswa.jurusan %></h4>
            <%= link_to  "Kembali", mahasiswas_path, :class => 'btn btn-info' %>
        </div>
    </div>
</div>